#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v26
# autospec commit: 99a7985
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : kmime
Version  : 25.04.1
Release  : 100
URL      : https://download.kde.org/stable/release-service/25.04.1/src/kmime-25.04.1.tar.xz
Source0  : https://download.kde.org/stable/release-service/25.04.1/src/kmime-25.04.1.tar.xz
Source1  : https://download.kde.org/stable/release-service/25.04.1/src/kmime-25.04.1.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : Library for handling mail messages and newsgroup articles
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 LGPL-2.0
Requires: kmime-data = %{version}-%{release}
Requires: kmime-lib = %{version}-%{release}
Requires: kmime-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
SPDX-License-Identifier: CC0-1.0

%package data
Summary: data components for the kmime package.
Group: Data

%description data
data components for the kmime package.


%package dev
Summary: dev components for the kmime package.
Group: Development
Requires: kmime-lib = %{version}-%{release}
Requires: kmime-data = %{version}-%{release}
Provides: kmime-devel = %{version}-%{release}
Requires: kmime = %{version}-%{release}

%description dev
dev components for the kmime package.


%package lib
Summary: lib components for the kmime package.
Group: Libraries
Requires: kmime-data = %{version}-%{release}
Requires: kmime-license = %{version}-%{release}

%description lib
lib components for the kmime package.


%package license
Summary: license components for the kmime package.
Group: Default

%description license
license components for the kmime package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n kmime-25.04.1
cd %{_builddir}/kmime-25.04.1
pushd ..
cp -a kmime-25.04.1 buildavx2
popd

%build
## build_prepend content
# avoid conflict
rm -rf po/zh_CN
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1747081402
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
## build_prepend content
# avoid conflict
rm -rf po/zh_CN
## build_prepend end
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1747081402
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kmime
cp %{_builddir}/kmime-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/kmime/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/kmime-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kmime/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/kmime-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kmime/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kmime-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kmime/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kmime-%{version}/README.md.license %{buildroot}/usr/share/package-licenses/kmime/cadc9e08cb956c041f87922de84b9206d9bbffb2 || :
cp %{_builddir}/kmime-%{version}/metainfo.yaml.license %{buildroot}/usr/share/package-licenses/kmime/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/locale/ar/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ast/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/be/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/bg/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/br/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/bs/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ca/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/cs/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/cy/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/da/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/de/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/el/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/eo/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/es/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/et/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/eu/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/fa/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/fi/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/fr/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/fy/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ga/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/gl/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/he/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/hi/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/hne/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/hu/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ia/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/it/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ja/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ka/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/kk/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/km/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ko/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/lt/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/lv/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/mk/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/mr/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ms/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/nb/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/nds/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ne/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/nl/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/nn/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/pa/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/pl/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/pt/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ro/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ru/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/sa/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/se/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/sk/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/sl/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/sq/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/sr/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/sr@ijekavian/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/sr@ijekavianlatin/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/sr@latin/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/sv/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ta/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/th/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/tr/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/ug/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/uk/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/uz/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/uz@cyrillic/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/wa/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/libkmime6_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/libkmime6_qt.qm
/usr/share/qlogging-categories6/kmime.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KPim6/KMime/KMime/Content
/usr/include/KPim6/KMime/KMime/ContentIndex
/usr/include/KPim6/KMime/KMime/HeaderParsing
/usr/include/KPim6/KMime/KMime/Headers
/usr/include/KPim6/KMime/KMime/MDN
/usr/include/KPim6/KMime/KMime/Message
/usr/include/KPim6/KMime/KMime/Types
/usr/include/KPim6/KMime/KMime/Util
/usr/include/KPim6/KMime/kmime/content.h
/usr/include/KPim6/KMime/kmime/contentindex.h
/usr/include/KPim6/KMime/kmime/headerparsing.h
/usr/include/KPim6/KMime/kmime/headers.h
/usr/include/KPim6/KMime/kmime/kmime_export.h
/usr/include/KPim6/KMime/kmime/mdn.h
/usr/include/KPim6/KMime/kmime/message.h
/usr/include/KPim6/KMime/kmime/types.h
/usr/include/KPim6/KMime/kmime/util.h
/usr/include/KPim6/KMime/kmime_version.h
/usr/lib64/cmake/KPim6Mime/KPim6MimeConfig.cmake
/usr/lib64/cmake/KPim6Mime/KPim6MimeConfigVersion.cmake
/usr/lib64/cmake/KPim6Mime/KPim6MimeTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KPim6Mime/KPim6MimeTargets.cmake
/usr/lib64/libKPim6Mime.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKPim6Mime.so.6.4.1
/usr/lib64/libKPim6Mime.so.6
/usr/lib64/libKPim6Mime.so.6.4.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kmime/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/kmime/7ff5a7dd2c915b2b34329c892e06917c5f82f3a4
/usr/share/package-licenses/kmime/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/kmime/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/kmime/cadc9e08cb956c041f87922de84b9206d9bbffb2
